// BetaXiv — content-addressed linking between a PDF and its summary/annotations.
//
// A PDF is keyed by the first 16 hex chars of the SHA-256 of its raw bytes — NOT its
// filename. So `.betaxiv/summaries/<id>.summary.json` and `.betaxiv/annotations/<id>.json`
// follow the paper through any rename or move: the id is recomputed from content.
//
// `.betaxiv/index.json` is a *rebuildable cache* mapping each PDF's workspace-relative path
// to its content id (plus byte size, so an unchanged PDF is not re-hashed on every open, and
// a human-readable title). It is deterministic — no machine-specific fields — so it can be
// committed and shared, or deleted and regenerated by re-hashing the PDFs. The summaries and
// annotations are keyed by id and never depend on the index being correct.

import * as vscode from "vscode";
import {
  type ContentIndex,
  type IndexEntry,
  INDEX_VERSION,
  INDEX_NOTE,
  contentIdFromBytes,
  relativizePath,
} from "./contentIndexCore";

// Re-export the pure core so callers have a single import surface (the core has no `vscode`
// dependency, so it stays unit-testable in plain Node).
export {
  type ContentIndex,
  type IndexEntry,
  CONTENT_ID_LEN,
  contentIdFromBytes,
  setTitle,
  repathEntries,
} from "./contentIndexCore";

function indexUri(wsFolder: vscode.WorkspaceFolder): vscode.Uri {
  return vscode.Uri.joinPath(wsFolder.uri, ".betaxiv", "index.json");
}

/** Workspace-relative POSIX path of a uri (no leading slash). Falls back to the basename. */
export function relPath(wsFolder: vscode.WorkspaceFolder, uri: vscode.Uri): string {
  return relativizePath(wsFolder.uri.path, uri.path);
}

/** Load index.json, or a fresh empty index if it is missing or corrupt (it is rebuildable). */
export async function loadIndex(wsFolder: vscode.WorkspaceFolder): Promise<ContentIndex> {
  try {
    const bytes = await vscode.workspace.fs.readFile(indexUri(wsFolder));
    const data = JSON.parse(new TextDecoder().decode(bytes));
    if (data && typeof data === "object" && data.entries && typeof data.entries === "object") {
      return { version: INDEX_VERSION, note: INDEX_NOTE, entries: data.entries };
    }
  } catch {
    // Missing, unreadable, or malformed → start empty. resolve() re-hashes and repopulates it.
  }
  return { version: INDEX_VERSION, note: INDEX_NOTE, entries: {} };
}

export async function saveIndex(wsFolder: vscode.WorkspaceFolder, index: ContentIndex): Promise<void> {
  const out: ContentIndex = { version: INDEX_VERSION, note: INDEX_NOTE, entries: index.entries };
  const body = JSON.stringify(out, null, 2) + "\n";
  await vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(wsFolder.uri, ".betaxiv"));
  await vscode.workspace.fs.writeFile(indexUri(wsFolder), new TextEncoder().encode(body));
}

/**
 * The ONLY way to write the index: load the current file, apply `fn`, and save iff `fn` reports
 * a change. Every mutation goes through a fresh read-modify-write, so a long-lived in-memory copy
 * can never overwrite entries another writer (a second panel, or the skill) added in the meantime.
 * (index.json is a rebuildable cache, so we don't lock — the residual race is a single-entry
 * last-writer-wins that self-heals on the next open.)
 */
export async function mutateIndex(
  wsFolder: vscode.WorkspaceFolder,
  fn: (index: ContentIndex) => boolean
): Promise<void> {
  const index = await loadIndex(wsFolder);
  if (fn(index)) await saveIndex(wsFolder, index);
}

/**
 * Resolve a PDF's content id, using index.json as a cache. Loads its own fresh snapshot, so it
 * never holds stale state. Returns `{ id, rel }` and, when the cache missed, a `write` entry the
 * caller should persist via {@link mutateIndex}. Returns `undefined` only if the PDF can't be read.
 *
 * Cache policy: a hit requires the recorded BYTE SIZE to still match — size is the only
 * deterministic, machine-independent signal kept in index.json (so it can be committed without
 * churn). This is a deliberate tradeoff: a replacement that preserves the EXACT same byte size is
 * not re-hashed and keeps the old id until the user regenerates the summary. Any size change, or a
 * missing entry, forces a re-hash.
 */
export async function resolveContentId(
  wsFolder: vscode.WorkspaceFolder,
  pdfUri: vscode.Uri
): Promise<{ id: string; rel: string; write?: IndexEntry } | undefined> {
  const rel = relPath(wsFolder, pdfUri);
  let size: number;
  try {
    size = (await vscode.workspace.fs.stat(pdfUri)).size;
  } catch {
    return undefined;
  }

  const cached = (await loadIndex(wsFolder)).entries[rel];
  if (cached && cached.size === size && cached.hash) {
    return { id: cached.hash, rel }; // cache hit — skip the re-hash
  }

  let bytes: Uint8Array;
  try {
    bytes = await vscode.workspace.fs.readFile(pdfUri);
  } catch {
    return undefined;
  }
  const id = contentIdFromBytes(bytes);
  return { id, rel, write: { hash: id, size, title: cached?.title } };
}
